import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import MainContainer from "./components/MainContainer";

export default function Home() {
  return (
    <MainContainer>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <h1 className={styles.title}>Тайтл </h1>
          <div>Главная страницы</div>
        </main>

        <footer className={styles.footer}>
          <div>Футер</div>
        </footer>
      </div>
    </MainContainer>
  );
}
